
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lms_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - lms_network

  db:
    image: mysql:8.0
    container_name: library_management_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library_management_db
      MYSQL_USER: lms_user
      MYSQL_PASSWORD: lms_user
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - lms_network

  nginx:
    image: nginx:latest
    container_name: lms_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - lms_network

volumes:
  mysql_data:

networks:
  lms_network:
    driver: bridge
